packages:
  [
    packages.direnv
    packages.ghcid
    packages.haskellPackages.brittany
    packages.haskellPackages.cabal-install
    packages.haskellPackages.hlint
    packages.tmux
    packages.tmux-up
  ]
